config/routes.rb
Rails.application.routes.draw do

  root to: "splash#index"
  get "/about", to: "splash#show", as: "about"

  #Routes for CRUD for Users
  get "/users", to: "users#index", as: "users"
  get "/signup", to: "users#new", as: "new_user"
  post "/users", to: "users#create", as: "create_user"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/archive", to: "users#archive", as: "user_archive"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"

  #Routes CRUD jobs
  get "/jobs/:id", to: "jobs#show", as: "job"
  get "/users/:id/jobs", to: "jobs#new", as: "new_job"
  post "/jobs", to:"jobs#create"
  get "/jobs/:id/edit", to: "jobs#edit", as: "edit_job"
  patch "/jobs/:id", to: "jobs#update"
  delete "/jobs/:id", to: "jobs#destroy"

  #Routes CRUD milestones
  get "/jobs/:id/new_milestone", to: "milestones#new", as: "new_milestone"
  post "/milestones", to: "milestones#create"
  get "/jobs/:id/milestones/edit", to: "milestones#edit", as: "edit_milestones"
  patch "/jobs/:id/milestones", to: "milestones#update"
  delete "/milestones/:id", to: "milestones#destroy", as: "delete_milestone"

  #Routes Crud contacts
  get "/contacts/:id", to: "contacts#show", as: "contact"
  get "/jobs/:id/contacts/new", to: "contacts#new", as: "new_contact"
  post "/contacts", to: "contacts#create"
  get "/contacts/:id/edit", to: "contacts#edit", as: "edit_contact"
  patch "/contacts/:id", to: "contacts#update"
  delete "/contacts/:id", to: "contacts#destroy", as: "delete_contact"

  #Routes for login form, logging in and logging out
  get "/login", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: "destroy_session"



end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  has_many :milestones, :dependent => :delete_all
  has_many :contacts, :dependent => :delete_all
  accepts_nested_attributes_for :milestones, :reject_if => lambda { |b| b[:title].blank? }

  default_scope {order('updated_at')}


  def find_last
    t_array = []
    self.milestones.each do |mil|
      if mil.status?
        t_array << mil
      end
      t_array.sort! { |a, b| a.id <=> b.id }
    end
    if t_array.length > 0
      return t_array[t_array.length-1]
    else
      return "You haven't dont anything yet."
    end
  end

  def truth_length
    truth_array = []
    self.milestones.each do |mil|
      if mil.status?
        truth_array << mil
      end
    end
    return truth_array.length
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :logged_in?, only: [:new, :create, :edit, :update, :destroy]

  def show
    set_job

  end


  def new
    @job = Job.new
  end


  def create
    @job = Job.new(job_params)

    #Adds milestones to job
    milestone_title = ["Applied", "Emailed", "Informational Interview", "Coding Challenge", "In Person Interview"]
    milestone_title.each do |mil_title|
      milestone = Milestone.new({title: mil_title})
      @job.milestones << milestone
    end


    current_user.jobs << @job
    if @job.save
      flash[:notice] = "Successfully created job"
      redirect_to edit_milestones_path(@job)
    else
      flash[:error] = @job.errors.full_messages.join(", ")
      redirect_to new_job_path
    end
  end


  def edit
    set_job
    unless current_user == @job.user
      redirect_to user_path(@user)
      flash[:notice] = "You can't edit that user"
    end
  end

  def update
    set_job
    if current_user == @job.user
      if @job.update_attributes(job_params)
        flash[:notice] = "Successfully updated job info"
        redirect_to job_path(@job)
      else
        flash[:error] = @job.error.full_messages.join(", ")
        redirect_to edit_job_path(@job)
      end
    else
      redirect_to job_path(current_job)
    end
  end


  def destroy
    set_job
    if current_user == @job.user
      @job.destroy
      flash[:notice] = "Successfully deleted job #{@job.title}"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "You can't delete that job."
      redirect_to job_path(@job)
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company, :title, :location, :url, :discovery, :interest_level, :notes, :archive, milestones_attributes: [:id, :title, :status])
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="container">
  <% if @job.user == current_user %>
    <%= link_to 'Back', job_path(@job), class:"btn btn-default pull-left btn-back" %>
  <% else %>
    <%= link_to 'Back', user_path(current_user), class:"btn btn-default pull-left btn-back" %>
  <% end %>
  <%= form_for @job, :html => {:class => "form-horizontal center-block"} do |f| %>
    <% if @job.user == current_user %>
      <h2 class="form-group title">Edit Job</h2>
    <% else %>
      <h2 class="form-group title">Add Job</h2>
    <% end %>
    <div class="form-group well">
      <div class="form-group">
        <%= f.label :company, "Company", class: "control-label sec-text" %>
        <%= f.text_field :company, :required => true, class: "form-control accent-text" %>
      </div>
      <div class="form-group">
        <%= f.label :title, "Job Title", class: "control-label sec-text" %>
        <%= f.text_field :title, :required => true, class: "form-control accent-text" %>
      </div>
      <div class="form-group">
        <%= f.label :location, "Location", class: "control-label sec-text" %>
        <%= f.text_field :location, class: "form-control accent-text" %>
      </div>
      <div class="form-group">
        <%= f.label :url, "URL Link to Application", class: "control-label sec-text" %>
        <%= f.text_field :url, class: "form-control accent-text" %>
      </div>
      <div class="form-group">
        <%= f.label :discovery, "How did you find it?", class: "control-label sec-text" %>
        <%= f.text_field :discovery, class: "form-control accent-text" %>
      </div>
      <div class="form-group">
        <%= f.label :interest_level, "How interested are you?", class: "control-label sec-text" %>
        <%= f.number_field :interest_level, placeholder: "1-5", min: 1, max: 5, class: "form-control accent-text" %>
      </div>
      <div class="form-group">
        <%= f.label :notes, "Extra Notes", class: "control-label sec-text" %>
        <%= f.text_area :notes, class: "form-control accent-text" %>
      </div>
      <div class="form-group pull-right archive">
        <%= f.label :archive, "Archive Job?", class: "control-label inline prim-text" %>
        <%= f.check_box :archive, class: "inline" %>
      </div>
      <div class="form-group">
        <%= f.submit "Submit", class: "btn btn-default sub-btn" %>
      </div>
    </div>
  <% end %>

</div>

app/views/jobs/show.html.erb
<div class="container">
  <%= link_to 'Back', root_path, class:"btn btn-default pull-left btn-back" %>
</div>
<div class="container text-center">
    <h2 class="title inline"><%= @job.title %></h2><h2 class="inline">&nbspat&nbsp</h2><h2 class="title inline"><%= @job.company %></h2>
</div>
<hr />

<div class="container show-container">

  <div class="col-md-6 center-block row">

    <div class="col-s-6 well" id="job-info">
      <h3 class="inline sub-title">Job Info</h3>
      <div class="inline pull-right icon-job">
        <%= link_to "", edit_job_path(@job.id), class: 'glyphicon glyphicon-pencil' %>
        <%= link_to "", @job, method: :delete, class: 'glyphicon glyphicon-remove' %>
      </div>
      <hr class="hr">
        <% if @job.interest_level? %>
          <h5 class="sec-text inline">Interest Level - </h5><h5 class="accent-text inline"><%= @job.interest_level %></h5>
          <br>
        <% end %>
        <% if @job.location? %>
          <h5 class="sec-text inline">Location - </h5><h5 class="accent-text inline"><%= @job.location %></h5>
          <br>
        <% end %>
        <% if @job.url? %>
          <h5 class="accent-text inline"><a class="accent-text" href=<%= @job.url %>>Link to Application</a></h5>
          <br>
        <% end %>
        <% if @job.discovery? %>
          <h5 class="sec-text inline">Found at - </h5><h5 class="accent-text inline"><%= @job.discovery %></h5>
          <br>
        <% end %>
        <% if @job.notes? %>
          <h5 class="sec-text inline">Notes - </h5><h5 class="accent-text inline"><%= @job.notes %></h5>
        <% end %>
    </div>

    <div class="col-s-6 well" id="contact-info">
      <h3 class="inline sub-title">Contact Info</h3>
      <div class="inline pull-right icon-job">
        <%= link_to "", new_contact_path, class: 'glyphicon glyphicon-plus' %>
      </div>
      <hr class="hr">
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <% @job.contacts.each do |contact| %>
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="heading<%= contact.id %>">
            <h4 class="panel-title">
              <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= contact.id %>" aria-expanded="false" aria-controls="collapseOne">
                <h5 class="accent-text inline"><%= contact.name %>'s </h5><h5 class="sec-text inline">&nbspInfo</h5>
              </a>
            </h4>
          </div>
          <div id="collapse<%= contact.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%= contact.id %>">
            <div class="panel-body">
              <% if contact.email? %>
                <h5 class="sec-text inline">Email - </h5><h5 class="accent-text inline"> <%= contact.email %></h5>
                <br>
              <% end %>
              <% if contact.phone? %>
                <h5 class="sec-text inline">Phone Number - </h5><h5 class="accent-text inline"> <%= contact.phone %></h5>
                <br>
              <% end %>
              <% if contact.web? %>
                <h5 class="sec-text inline">Website - </h5><h5 class="inline"> <a class="accent-text" href=<%= contact.web %>> <%= contact.web %></a></h5>
                <br>
              <% end %>
              <% if contact.notes? %>
                <h5 class="sec-text inline">Notes - </h5><h5 class="accent-text inline"> <%= contact.notes %></h5>
              <% end %>
              <div class="inline pull-right">
                <%= link_to "", edit_contact_path(contact), class: 'glyphicon glyphicon-pencil' %>
                <%= link_to "", delete_contact_path(contact), method: :delete, class: 'glyphicon glyphicon-remove' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>

  </div>

  <div class="col-md-6 row center-block">

    <div class="col-lg-4 pull-right well" id="mil-info">
      <h3 class="inline sub-title">Milestones</h3>
      <div class="inline pull-right icon-job">
        <%= link_to "", new_milestone_path, class: 'glyphicon glyphicon-plus' %>
        <%= link_to "", edit_milestones_path(@job), class: 'glyphicon glyphicon-pencil' %>
      </div>
      <hr class="hr">
      <% @job.milestones.each do |milestone| %>
        <%= check_box_tag "milestone", "status", milestone.status, disabled: true %>
        <% if milestone.status? %>
          <h5 class="accent-text inline"><%= milestone.title %></h5> <h5 class="prim-text inline"> - <%= time_ago_in_words(milestone.updated_at) %> ago</h5>
        <% else %>
          <h5 class="accent-text inline"><%= milestone.title %></h5>
        <% end %>
        <div class="pull-right icon-job">
          <%= link_to "", delete_milestone_path(milestone), method: :delete, class: 'glyphicon glyphicon-remove icon-job pull-right' %>
        </div>
        <br />
      <% end %>
    </div>

  </div>

</div>