config/routes.rb
Rails.application.routes.draw do

  root to: "splash#index"
  get "/about", to: "splash#show", as: "about"

  #Routes for CRUD for Users
  get "/users", to: "users#index", as: "users"
  get "/signup", to: "users#new", as: "new_user"
  post "/users", to: "users#create", as: "create_user"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/archive", to: "users#archive", as: "user_archive"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"

  #Routes CRUD jobs
  get "/jobs/:id", to: "jobs#show", as: "job"
  get "/users/:id/jobs", to: "jobs#new", as: "new_job"
  post "/jobs", to:"jobs#create"
  get "/jobs/:id/edit", to: "jobs#edit", as: "edit_job"
  patch "/jobs/:id", to: "jobs#update"
  delete "/jobs/:id", to: "jobs#destroy"

  #Routes CRUD milestones
  get "/jobs/:id/new_milestone", to: "milestones#new", as: "new_milestone"
  post "/milestones", to: "milestones#create"
  get "/jobs/:id/milestones/edit", to: "milestones#edit", as: "edit_milestones"
  patch "/jobs/:id/milestones", to: "milestones#update"
  delete "/milestones/:id", to: "milestones#destroy", as: "delete_milestone"

  #Routes Crud contacts
  get "/contacts/:id", to: "contacts#show", as: "contact"
  get "/jobs/:id/contacts/new", to: "contacts#new", as: "new_contact"
  post "/contacts", to: "contacts#create"
  get "/contacts/:id/edit", to: "contacts#edit", as: "edit_contact"
  patch "/contacts/:id", to: "contacts#update"
  delete "/contacts/:id", to: "contacts#destroy", as: "delete_contact"

  #Routes for login form, logging in and logging out
  get "/login", to: "sessions#new", as: "new_session"
  post "/sessions", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: "destroy_session"



end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :jobs, :dependent => :delete_all
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email
  validates :email, format: {with: /@/}

  def self.confirm(params)
      @user = User.find_by({email: params[:email]})
      @user.try(:authenticate, params[:password])
  end

  def is_authorized?
    current_user == @user
  end

  def alive
    alive = []
    self.jobs.each do |job|
      if !job.archive?
        alive << job
      end
    end
    return alive.sort! { |a,b| b.updated_at <=> a.updated_at}
  end


  def dead
    dead = []
    self.jobs.each do |job|
      if job.archive?
        dead << job
      end
    end
    return dead.sort! { |a,b| b.updated_at <=> a.updated_at}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?, only: [ :edit, :update, :destroy]
  before_action :logged_out?, only: [:new, :create]

  def index
    redirect_to @user
  end

  def show
    set_user
    @jobs = set_user.alive
  end

  def archive
    set_user
    @jobs = set_user.dead
  end

  def new
    @user = User.new
  end

  def create
    fixed_interest = user_params[:interest]
    params = user_params
    params[:interest] = fixed_interest.split(",")
    @user = User.create(params)
    if @user.save
      login(@user)
      redirect_to @user
    else
      flash[:error] = "Please check your email: invalid format or already in use."
      redirect_to new_user_path
    end
  end

  def edit
    set_user
    unless current_user == @user
      redirect_to user_path(@user)
      flash[:notice] = "You can't edit that user"
    end
  end

  def update
    set_user
    if current_user == @user
      if @user.update_attributes(user_params)
        flash[:notice] = "Successfully updated user info"
        redirect_to user_path(@user)
      else
        flash[:error] = @user.error.full_messages.join(", ")
        redirect_to edit_user_path(@user)
      end
    else
      redirect_to user_path(current_user)
    end
  end

  def destroy
    set_user
    if current_user == @user
      @user.destroy
      flash[:notice] = "Successfully deleted user #{@user.last_name}"
      redirect_to root_path
    else
      flash[:notice] = "You can't delete that user."
      redirect_to user_path(@user)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :interest)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :html => {:class => "form-horizontal center-block"} do |f| %>

  <% if current_user == @user %>
    <h2 class="form-group title"><%= @user.first_name%>'s info</h2>
  <% else %><br>
    <h2 class="form-group title">Signup</h2>
  <% end %>
  <div class="form-group well">
    <div class="form-group">
      <%= f.label :first_name, "First Name", class: "control-label" %>
      <%= f.text_field :first_name, :required => true, class: "form-control accent-text" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, "Last Name", class: "control-label" %>
      <%= f.text_field :last_name, :required => true, class: "form-control accent-text" %>
    </div>
    <div class="form-group">
      <%= f.label :email, "Email", class: "control-label" %>
      <%= f.text_field :email, :required => true, class: "form-control accent-text" %>
    </div>
    <% if current_user == @user %>
      <div class="form-group">
        <%= f.label :password, "Password", class: "control-label" %>
        <%= f.password_field :password, class: "form-control accent-text" %>
      </div>
    <% else %>
      <div class="form-group">
        <%= f.label :password, "Password", class: "control-label" %>
        <%= f.password_field :password, :required => true, class: "form-control accent-text" %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :interest, "Interest (separate by '\,')", class: "control-label" %>
      <%= f.text_field :interest, placeholder: "Ex. Mechanical Engineering, Software Engineering", class: "form-control accent-text" %>
    </div>
    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-default sub-btn" %>
    </div>
  </div>
<% end %>

app/views/users/archive.html.erb
<div class="container">
  <%= link_to 'Back', root_path, class:"btn btn-default pull-left btn-back" %>
</div>
<div class="container">
  <div class="text-center">
    <h1 class="title"><%= @user.first_name %>'s Archived Jobs</h1>
  </div>
</div>
<hr />

<% if @jobs.length > 0 %>
  <div class="job-container col-md-8 col-md-offset-2">
    <table class="table table-hover well">
      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td>
              <h4 class="accent-text inline"><%= link_to "#{job.title}", job_path(job.id), class: "accent-text" %></h4>
              <h5 class="sec-text inline">at</h5>  <h4 class="accent-text inline"><%= job.company %>.</h4>
              <% if job.truth_length > 0 %>
                <h5 class="sec-text inline text-center">Last Milestone</h5>
                <h4 class="accent-text inline text-center"><%= job.find_last.title %> <%= time_ago_in_words(job.find_last.updated_at) %> ago</h4>
              <% else %>
                <h5 class="sec-text inline text-center">No Milestones</h5>
              <% end %>
              <div class="pull-right icon">
                <%= link_to "", edit_job_path(job.id), class: 'glyphicon glyphicon-pencil' %>
                <%= link_to "", job, method: :delete, class: 'glyphicon glyphicon-remove' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="text-center">
    <h3>You have no jobs archived.</h3>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Interest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.interest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="form-container">
  <%= link_to 'Back', root_path, class:"btn btn-default pull-left btn-back" %>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="inline prof-btns">
  <%= link_to 'Edit Profile', edit_user_path(@user.id), method: :get, class:"btn btn-xs btn-back" %>
  <%= link_to 'Remove Profile', @user, method: :delete, class:"btn btn-xs btn-back" %>
</div>
<div class="inline pull-right" id="archive-btn" %>
  <%= link_to 'Archived Jobs', user_archive_path(@user), method: :get, class: "btn btn-back" %>
</div>
<div class="container">
  <div class="text-center">
    <% if @user.jobs.length == 0 %>
      <div>
       	<h1 class="title">Welcome <%= @user.first_name %> <%= @user.last_name %></h1>
      </div>
        <h3>To get started click the button below!</h3>
    <% else %>
      <h1 class="title text-center">Hello <%= @user.first_name %></h1>
    <% end %>
  </div>
</div>

<div class="button text-center">
  <%= button_to "Add Job", new_job_path, method: :get, class: 'btn btn-add center-block'  %>
</div>
<hr />
<% if @user.jobs.length > 0 %>
  <div class="job-container col-md-8 col-md-offset-2">
    <table class="table table-hover well">
      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td>
              <h4 class="accent-text inline"><%= link_to "#{job.title}", job_path(job.id), class: "accent-text" %></h4>
              <h5 class="sec-text inline">at</h5>  <h4 class="accent-text inline"><%= job.company %>.</h4>
              <% if job.truth_length > 0 %>
                <h5 class="sec-text inline text-center">Last Milestone</h5>
                <h4 class="accent-text inline text-center"><%= job.find_last.title %> <%= time_ago_in_words(job.find_last.updated_at) %> ago</h4>
              <% else %>
                <h5 class="sec-text inline text-center">No Milestones</h5>
              <% end %>
              <div class="pull-right icon">
                <%= link_to "", edit_job_path(job.id), class: 'glyphicon glyphicon-pencil' %>
                <%= link_to "", job, method: :delete, class: 'glyphicon glyphicon-remove' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>